<?php

return [
    [
        'name' => 'Saw',
        'tagline' => 'How much blood will you spill to stay alive?',
        'image_url' => 'https://st.kp.yandex.net/images/film_iphone/iphone360_64187.jpg',
        'video_url' => 'https://www.youtube.com/watch?v=S-1QgOMQ-ls',
        'slug' => 'saw',
        'global_rating' => '7.7',
        'country' => 'USA',
        'year' => '2004',
        'duration' => '01:43:00',
        'local_rating' => '2.5',
        'producer_id' => '1',
        'mpaa_id' => '1',
    ],
    [
        'name' => 'Saw II',
        'tagline' => 'Oh yes, there will be a lot of blood',
        'image_url' => 'https://st.kp.yandex.net/images/film_iphone/iphone360_86206.jpg',
        'video_url' => 'https://www.youtube.com/watch?v=bYgkU9b3OjI',
        'slug' => 'saw-ii',
        'global_rating' => '7.3',
        'country' => 'USA',
        'year' => '2005',
        'duration' => '01:33:00',
        'local_rating' => '4.3',
        'producer_id' => '1',
        'mpaa_id' => '1',
    ],
    [
        'name' => 'Saw III',
        'tagline' => 'To live or die? The choice is yours',
        'image_url' => 'https://st.kp.yandex.net/images/film_iphone/iphone360_184417.jpg',
        'video_url' => 'https://www.youtube.com/watch?v=iJjPd8KcrC4',
        'slug' => 'saw-iii',
        'global_rating' => '7.0',
        'country' => 'USA',
        'year' => '2006',
        'duration' => '01:48:00',
        'local_rating' => '4.2',
        'producer_id' => '1',
        'mpaa_id' => '1',
    ],
];
