<?php

namespace common\tests\unit\repositories;

use Codeception\Test\Unit;
use common\fixtures\CommentFixture;
use common\fixtures\FilmGenreFixture;
use frontend\repositories\CommentRepository;
use Yii;
use yii\helpers\ArrayHelper;


/**
 * Login form test
 */
class CommentTest extends Unit
{
    /**
     * @var \common\tests\UnitTester
     */
    protected $tester;
    protected $commentRepository;

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        $this->commentRepository = Yii::createObject(CommentRepository::class);
    }

    /**
     * @return array
     */
    public function _fixtures()
    {
        return [
            'filmGenre' => [
                'class' => CommentFixture::class,
                'dataFile' => codecept_data_dir() . 'filmGenre.php'
            ],
        ];
    }

    public function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
    }

    public function testGetAllRootCommentsWithFilmId()
    {
        $data = $this->commentRepository->getAllRootCommentsWithFilmId(1);
        $comment = $this->tester->grabFixture('comment', '0');
        $this->assertEquals($comment, $data);
    }

    public function testGetAllRootCommentsWithProducerActorId()
    {
        $data = $this->commentRepository->getAllRootCommentsWithProducerActorId(1);
        $comment = $this->tester->grabFixture('comment', '1');
        $this->assertEquals($comment, $data);
    }


}
