<?php

namespace common\tests\unit\repositories;

use Codeception\Test\Unit;
use common\fixtures\FilmFixture;
use frontend\repositories\FilmRepository;
use Yii;
use yii\helpers\ArrayHelper;


/**
 * Login form test
 */
class FilmTest extends Unit
{
    /**
     * @var \common\tests\UnitTester
     */
    protected $tester;
    protected $filmRepository;
    protected $films;

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        $this->filmRepository = Yii::createObject(FilmRepository::class);
    }

    /**
     * @return array
     */
    public function _fixtures()
    {
        return [
            'film' => [
                'class' => FilmFixture::class,
                'dataFile' => codecept_data_dir() . 'film.php',
            ],
        ];
    }

    public function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
        $this->films = $this->tester->grabFixture('film');
    }

    public function testGetColumnsBy()
    {
        $data = $this->filmRepository->getColumnsBy(['id'], ['producer_id' => 1]);
        $this->assertEquals(ArrayHelper::getColumn($this->films, 'id'), ArrayHelper::getColumn($data, 'id'));
    }

    public function testGetColumnsById()
    {
        $filmNames = ArrayHelper::getColumn($this->films, 'name');
        $data = $this->filmRepository->getColumnsById(['name'], [1]);
        $this->assertEquals($filmNames[0], $data[0]['name']);
    }

    public function testGetColumnsByProducerId()
    {
        $data = $this->filmRepository->getColumnsByProducerId(['name'], 1);
        $this->assertEquals(ArrayHelper::getColumn($this->films, 'name'), ArrayHelper::getColumn($data, 'name'));
    }

    public function testGetIdsByProducerId()
    {
        $data = $this->filmRepository->getIdsByProducerId(1);
        $this->assertEquals(ArrayHelper::getColumn($this->films, 'id'), ArrayHelper::getColumn($data, 'id'));
    }

    public function testGetSlugById()
    {
        $data = $this->filmRepository->getSlugById(1);
        $this->assertEquals(ArrayHelper::getValue($data, '0.slug'), ArrayHelper::getValue($data, '0.slug'));
    }

}
