<?php

namespace common\tests\unit\repositories;

use Codeception\Test\Unit;
use common\fixtures\FilmGenreFixture;
use frontend\repositories\FilmGenreRepository;
use Yii;
use yii\helpers\ArrayHelper;


/**
 * Login form test
 */
class FilmGenreTest extends Unit
{
    /**
     * @var \common\tests\UnitTester
     */
    protected $tester;
    protected $filmGenreRepository;
    protected $filmGenres;

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        $this->filmGenreRepository = Yii::createObject(FilmGenreRepository::class);
    }

    /**
     * @return array
     */
    public function _fixtures()
    {
        return [
            'filmGenre' => [
                'class' => FilmGenreFixture::class,
                'dataFile' => codecept_data_dir() . 'filmGenre.php'
            ],
        ];
    }

    public function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
        $this->filmGenres = $this->tester->grabFixture('filmGenre');
    }

    public function testGetGenreIdsByFilmId()
    {
        $data = $this->filmGenreRepository->getGenreIdsByFilmId(1);
        $this->assertEquals([1,2,3], ArrayHelper::getColumn($data, 'genre_id'));
    }

    public function testGetFilmIdsByGenreId()
    {
        $data = $this->filmGenreRepository->getFilmIdsByGenreId(1);
        $this->assertEquals([1,2,3], ArrayHelper::getColumn($data, 'film_id'));
    }

}
